robot:
  client_name: "newbot"
  broker_ip: "192.168.137.1"

mqtt:
  subscriptions:
    - "robot/newbot/action_group"
    - "robot/newbot/script"
    - "robot/newbot/stop"
    - "robot/newbot/heartbeat"
    - "robot/newbot/status"

startup:
  initial_script: "" 
 