robot:
  client_name: "testbot"
  broker_ip: "127.0.0.1"

mqtt:
  subscriptions:
    - "robot/testbot/action_group"
    - "robot/testbot/script"
    - "robot/testbot/stop"
    - "robot/testbot/heartbeat"
    - "robot/testbot/status"

startup:
  initial_script: "" 
 